# Generated by Django 3.2.25 on 2024-10-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_alter_bloginfo_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
